### ISSUE TITLE
clock / ntp module needs cleanup

### ISSUE THREAD

**Issue by michaelb42** [ethersex/ethersex#368]
The clock / ntp module needs some love:
- NTPD support uses TIMER_8_AS_1_* aka CLOCK_CRYSTAL but does not depend on it
- NTP (debug) options and macros are randomly distributed over the code and various config.in
- NTP module should have a config.in in its own subdirectory
- overall clock module code size can be reduced by adding some dependencies and #ifdefs

**Comment by eku** [comment]
Finished with f808bed5838371bd919c2ea02e474146374edb75?
