### ISSUE TITLE
onewire negative temperature isnt working

### ISSUE THREAD

**Issue by florian-asche** [ethersex/ethersex#379]
Hallo,

Ich habe gerade nochmal extra komplett von vorne angefangen. Also aktuelle Ethersex Version (Master) aus dem Repository (git clone git://github.com/ethersex/ethersex.git) gezogen, dann eine IP konfiguriert, den Port im Pinning für das NETIO angepasst und Debug aktiviert.

Ich verwende das NETIO von Pollin, Atmega32 ohne anpassungen.

Dann mache ich (ohne Polling):
    1w convert
    OK
    1w get 289dfb0402000072
    297.74

Dasselbe Ergebnis wie bei dem Webserver (http://192.168.0.65/ow.ht) Besteht das Problem also nur beim Onewire ohne Polling?

Ich habe dann mal versucht das Onewire Polling zum Laufen zu bekommen... 

1w name set 0 289dfb0402000072 netio

1w list
289dfb0402000072        netio   319.31  1
OK

Selbes Problem...

**Comment by Mike73A** [comment]
Hallo,

*/
 * ich hoffe, das liest noch jemand ;) 
 * Florian, könntest du den issue nochmal auf machen und die hier beschriebene Änderung  
 * einbringen? 
*/

Das Problem habe ich auch festgestellt und bin - unabhängig von diesem issue - zu im Grunde der gleichen Lösung gekommen. 

Das Problem besteht darin, dass die Temperaturwerte in temp.val **15Bit signed int**  sind, während in der Funktion itoa_fixedpoint von **uint16_t** ausgegangen wird. Dummerweise liegt das sign-Bit dann in bit 15 (0x4000) und nicht in Bit 16 ( 0x8000) wie sonst. Damit ist die Behandlung negativer Werte in der Funktion wirkungslos. Abhilfe schafft die "Umrechnung", wie oben vorgeschlagen  _temp.val&0x4000?(0x8000|temp.val):temp.val_ .  Die Ersetzung müsste an zwei Stellen in hardware/onewire/onewire_ecmd.c gemacht werden. Dann klappts mit der Datstellung sowohl in "1w list" ( mit Werten) als auch in "1w get" . 

Ich bin leider mit git und pull requests nicht gut genug vertraut, so dass ich den Patch nicht als solchen zur Verfügung stellen kann. 

grüße
Mike

**Comment by mwue** [comment]
Ich gleich nochmal  .. jetzt hab ich das mit den Pull-Requests rausgefunden. Habs gleich selber reingestellt. Mal schauen, ob das durchgeht. 
Danke
Mike

**Comment by florian-asche** [comment]
Alles klar ;)
By the way, du hast nicht zufällig ein bisschen Zeit um den MQTT beizubringen?

**Comment by eku** [comment]
Github isn't a support forum. Please use either irc or mailing list.
