### ISSUE TITLE
ESEND with variables?

### ISSUE THREAD

**Issue by kpwg** [ethersex/ethersex#384]
Is it possible to send variables with ESEND? Actually it works only with static sequences.

**Comment by eku** [comment]
The current implemtation accepts fixed strings from within flash. Supporting variable strings from RAM requires API changes in ecmd_sender_net and Control6.

As a work around one could use ECMD over UDP (uecmd_sender_send_command), which accepts a string in RAM.

**Comment by eku** [comment]
Please check if this https://github.com/eku/ethersex/tree/esend fits your requirements.

**Comment by eku** [comment]
No response from kpwg, so closing this request.
