### ISSUE TITLE
watch IO changes requires full featured I/O

### ISSUE THREAD

**Issue by kpwg** [ethersex/ethersex#387]
"watch IO changes (and react)" requires full featured I/O abstraction model. It doesn't work with "simple I/O", even though selectable.

**Comment by eku** [comment]
Yes, the required dependency is missing from the menuconfig.

**Comment by michaelb42** [comment]
Missing default definitions in the portio stuff - try applying the diff, choose simple / full-featured once to set the defines and it should work as expected. To make this work out-of-the-box one must regenerate the profiles again...
:running:

https://gist.github.com/michaelb42/ba2696f0e96027f6a214

**Comment by kpwg** [comment]
Thanks, it works!
