### ISSUE TITLE
ECMD: adc get broken

### ISSUE THREAD

**Issue by eku** [ethersex/ethersex#405]
Since a651597db5c8c2692fd2705a30bcf16ace9d56a the ECMD `adc get` results in rubish data;

`1L8 1K2 1IF 1HF 1R8 1KF 1V0 1R7`

**Comment by eku** [comment]
https://github.com/ethersex/ethersex/blob/master/hardware/adc/adc_ecmd.c#L65 expects an 8 bit value.

**Comment by AnDann** [comment]
Add LO8(adc) seems to fix this

**Comment by AnDann** [comment]
the hi4 macro was wrong PR #407 should fix that

**Comment by eku** [comment]
NO, the HI4 macro is correct. The caller has to make sure that it provies a 8bit value to the macro.
