### ISSUE TITLE
make dependencies for meta_magic_scheduler

### ISSUE THREAD

**Issue by eku** [ethersex/ethersex#413]
After ```make menuconfig``` the meta_magic_scheduler isn't rebuilt.

**Comment by michaelb42** [comment]
This bug is not restricted to the new timer framework, it's a long unnoticed one also in the head branch.

meta.c and meta.h do not depend on meta.defines. Changing meta.defines via make menuconfig does not trigger a regeneration of these source files.

#414 fixes this one. Please test.

**Comment by eku** [comment]
The timestamp ```built on <date><time>``` isn't updated on each new build.

**Comment by eku** [comment]
Tested your fix, but doesn't work for me (gnu make 3.82).

**Comment by michaelb42** [comment]
The timestamp mentioned above is defined in config.h and evaluated during compile time of ethersex.c - if this src is *not* rebuild on each and every change to config.h / autoconf.h something is horribly wrong with your setup.

Second - works for me :wink: Please provide a "make -d" log without / with the fix applied from a fresh clean build and a build where only a value_XXXX element is changed via menuconfig, e.g. the hostname.

**Comment by eku** [comment]
If I change a source file (not ethesex.c), the timestamp is not updated. Since it says "built on" and not "configured on" the info is misleading.
