### ISSUE TITLE
compile-time i2c adress for 24Cxx eeproms is wrong

### ISSUE THREAD

**Issue by michaelb42** [ethersex/ethersex#439]
All - according to the datasheets - Atmel 24Cxx have the same base i2c address of 0x50, not 80 as used in hardware/i2c/master/i2c_24CXX.h.

**Comment by michaelb42** [comment]
:-1:

**Comment by eku** [comment]
0x50 == 80

**Comment by michaelb42** [comment]
Yepp. Never analyze code when you're feverish and used pain killers... :grinning:
