### ISSUE TITLE
Teensy web server

### ISSUE THREAD

**Issue by streamnsight** [ethersex/ethersex#441]
Hello,

Sorry for the ignorant question here, but I'm wondering if this project could be used to get a web server running on a Teensy via USB ?

If I understand this correctly, this is the network stack. I came to this page looking for USBnet and it seems like it supports networking through USB. Is this correct? (The Wiki is good at explaining how to setup and run but doesn't explain much of what it actually does)

If this is correct, then there is still a stretch between having a network stack going and serving HTTP requests... 
Has anyone worked on this in here?

I'd appreciate your input / guidance.

Thanks

**Comment by eku** [comment]
This is not a support forum. Use the mailing list or IRC channel.
