### ISSUE TITLE
How do I contribute to the wiki?

### ISSUE THREAD

**Issue by tobox** [ethersex/ethersex#459]
Maybe this is the completely wrong place to ask this question, but I did not find a better place. 

I wanted to make a small modification to the wiki, and could not find out how to create an account. Am I missing something obvious, or where is access to the wiki documented?

**Comment by eku** [comment]
Editing the [wiki}(www.ethersex.de) requires an account (spam protection). Accounts are created by the admins of the wiki on demand. Join our IRC channel #ethersex at freenode.net to meet the admins an request an account.
