### ISSUE TITLE
compiler error mit named pins

### ISSUE THREAD

**Issue by Campino63** [ethersex/ethersex#461]
Hallo,
bei Verwendung von named pins bricht der compiler mit vielen errors in `meta.c` ab.
Hier die verwendete Pin Konfiguration:

`# PIN | IN/OUT | When active? | Name`
`#-----+--------+--------------+----------------`
`PA5 OUTPUT  HIGH        OPEN`
`PA4 OUTPUT  HIGH        CLOSE`
`PC0	OUTPUT	HIGH		RELAIS1`
`PC1	OUTPUT	HIGH		RELAIS2`
`PC2	OUTPUT	HIGH		RELAIS3`
`PC3	OUTPUT	HIGH		RELAIS4`
`PC4	OUTPUT	HIGH		RELAIS5`
`PC5	OUTPUT	HIGH		RELAIS6`
`PC6	OUTPUT	HIGH		RELAIS7`
`PC7	OUTPUT	HIGH		RELAIS8`

Über `make menuconfig` wurde `Pollin AVR Net-IO` geladen. IP-Adresse angepasst und obige pin Konfiguration gewählt. Bei Bedarf kann ich auch `.config` nachreichen. Aber dort ist nichts weiter konfiguriert.

Wenn ich in `Makefile` die Zeile:
`meta.c: $(y_META_SRC) meta.defines`
in 
`meta.c: $(y_META_SRC)`
ändere, dann läuft der build durch. Die Pins lassen sich über ECMD mit Namen ansprechen. Nebenwirkungen habe ich bisher keine bemerkt.

Per `git bisect` habe ich den commit 32c664 als Verursacher ermittelt.

**Comment by michaelb42** [comment]
For some mysterious reason (m4 diverts?) the build only breaks when the named pin config is used. Looking at the effect of the meta.define prerequisite one could expect things to be broken in general... :-1:
