### ISSUE TITLE
static varables in resolv.c + dhcp.c

### ISSUE THREAD

**Issue by ferbar** [ethersex/ethersex#494]
Please let me know what you think of these changes. Is there any reason to make the loop variables static?
This change saves the huge amount of 8 bytes global data.

https://github.com/ferbar/ethersex/commit/0360961be9f9795c1ee4a39a582707fa5192c5e8

in dhcp.c one PSTR() is missing, saves some bytes ram, too:

https://github.com/ferbar/ethersex/commit/3566151d1f6f5041fe2d5e4e90718d4e569241eb#diff-a5c2bff26e6f1af2ceaa1d477674d64a

**Comment by eku** [comment]
Please file a PR, excluding httplog.c.

**Comment by ferbar** [comment]
see #495

**Comment by michaelb42** [comment]
#495 merged by @eku
