### ISSUE TITLE
Changeset b827d22 breaks menuconfig menus for usart

### ISSUE THREAD

**Issue by stefan-muc** [ethersex/ethersex#503]
git checkout ca6f98d
make menuconfig
Go to Protocols ---> ECMD support ---> 
Enable USART (if not enabled)
Press [Enter] on "Ecmd usart select"
New dialogue for selecting usart appears

git checkout b827d22
do the same as above
No dialogue appears.

`./MCradiolists: line 12: syntax error near unexpected token `('
./MCradiolists: line 12: `      function  ()            { l_choice '  Ecmd usart select' "  ECMD_SERIAL_USART_USART_" "" "" ;}'
`

**Comment by michaelb42** [comment]
@eku It seems that the promicro PR #500 breaks the USART handling

**Comment by eku** [comment]
@michaelb42 works perfectly on Fedora 26. Could you please provide the temporary generated files. thx

**Comment by michaelb42** [comment]
@stefan-muc could you please provide the files in question to @eku?

**Comment by stefan-muc** [comment]
Asked @michaelb42 on details what "the temporary generated files" are.

Here there are:
[MCmenu.txt](https://github.com/ethersex/ethersex/files/1435623/MCmenu.txt)
[MCradiolists.txt](https://github.com/ethersex/ethersex/files/1435624/MCradiolists.txt)
