### ISSUE TITLE
Teensy build incompatible with 1wire naming support

### ISSUE THREAD

**Issue by stefan-muc** [ethersex/ethersex#505]
use config from #504 and enable Onewire naming support

make -> success

Enable General Setup ---> Teensy build

make -> error
`hardware/onewire/onewire.o: In function `ow_names_save':
ethersex/hardware/onewire/onewire.c:896: undefined reference to `eeprom_write_block_hack'
ethersex/hardware/onewire/onewire.c:899: undefined reference to `eeprom_get_chksum'
ethersex/hardware/onewire/onewire.c:899: undefined reference to `eeprom_write_block_hack'
`

**Comment by eku** [comment]
Duplicate #419.
