### ISSUE TITLE
gawk-4.2.0 breaks scripts/Menuconfig

### ISSUE THREAD

**Issue by michaelb42** [ethersex/ethersex#506]
Noticed on gentoo unstable: Updating from gawk-4.1.4 to gawk-4.2.0 breaks scripts/Menuconfig.

MCmenu* etc. look all very weired, closing brackets are missing, etc. Needs further digging.

**Comment by mguentner** [comment]
confirmed.

`scripts/Menuconfig` with gawk-4.2.1 works again

**Comment by michaelb42** [comment]
Ack. gawk 4.2.1 works again. So, no further digging, no fix (at least for now).
