### ISSUE TITLE
Can't make menuconfig - .config file missing / ncurses

### ISSUE THREAD

**Issue by TheSmartGerman** [ethersex/ethersex#509]
I did a new Ubuntu/ethersex installation according to the tutorial http://www.ethersex.de/index.php/Quick_Start_Guide.

When I try to make menuconifg, I'll get a lot of errors .config file is missing. At the end, I'll also tells me unable to find Ncurses libraries. 

I checked the Ncurses libraries i tried this: https://stackoverflow.com/questions/23050188/cant-make-menuconfig

but no success...

**Comment by TheSmartGerman** [comment]
Ok, got it!
Missing: Native GCC-Compiler (for the lxdialog utility required by make menuconfig) 

The guide should be adjusted to this: `apt-get install **gcc** gcc-avr avr-libc binutils-avr m4 gawk libncurses5-dev make dialog git-core avrdude`

**Comment by eku** [comment]
@TheSmartGerman why don't you just add the missing information to the wiki?

**Comment by TheSmartGerman** [comment]
I don't have a Login. The Login page don't give you the Option to create a
new user. Only as a user I'm able to edit the wiki

2017-11-16 19:21 GMT+01:00 Erik Kunze <notifications@github.com>:

**Comment by TheSmartGerman** [comment]
Wer verwaltet das Wiki? Ich würde mich da gerne ein wenig einbringen. Aber
es bit keine Seite zum einen neuen Account zu erstellen...

2017-11-24 11:59 GMT+01:00 Benedikt Geiger <benegei@gmail.com>:

**Comment by eku** [comment]
@TheSmartGerman wiki account created. You should have received an email with login credentials.

**Comment by TheSmartGerman** [comment]
Ok thx 

Am 14. Dezember 2017 20:56:20 MEZ schrieb Erik Kunze <notifications@github.com>:
>@TheSmartGerman wiki account created. You should have received an email
>with login credentials.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ethersex/ethersex/issues/509#issuecomment-351818791

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
