### ISSUE TITLE
glcd does not compile with default config

### ISSUE THREAD

**Issue by michaelb42** [ethersex/ethersex#550]
### Expected behavior
Runing make mrproper, make menuconfig and choosing a decent default config like Pollin AVR Net-IO should at least produce a configuration that compiles smoothly
### Actual behavior
compile in subdir glcd bails out with an `#error unsupported HW` and lots of warnings
### Test code
make mrproper
make menuconfig
--> choose default config, save
make

Same behavoiur, if I try it with a fresh git clone and make menuconfig.
### Ethersex version
Which Git revision are you on?
HEAD
### Hardware
Describe which AVR device you use and document any special hardware setup
required to reproduce the problem.
Tried default config for Pollin AVR Net-IO and AVR NET-IO (w( addon board)

**Comment by eku** [comment]
Confirmed
```
In file included from hardware/lcd/glcd/glcd.c:69:
hardware/lcd/glcd/glcd_mono.c:371:2: error: #error unsupported HW
  371 | #error unsupported HW
      |  ^~~~~
In file included from hardware/lcd/glcd/glcd.c:73:
hardware/lcd/glcd/glcd_color.c:247:2: error: #error unsupported HW
  247 | #error unsupported HW
      |  ^~~~~
```
